            <td width="100%" bgcolor="#F4F4F4" height="25" valign="middle" style="border-top: 1 solid #C0C0C0">
        <p align="center" class="9ptV"><font face="Tahoma" size="1">Copyright
        &copy; Text by </font><a href="mailto:x155110@poczta.wp.pl" class="link2"><font color="#437BBA" face="Tahoma" size="1">Arek
        Krolak</font></a><font face="Tahoma" size="1"> &amp; Design by </font><a href="mailto:lupusfm@poczta.onet.pl" class="link2"><font color="#437BBA" face="Tahoma" size="1">Dr.
        Loopus</font></a><font face="Tahoma" size="1"> 2001-2004</font></td>
