                      <script language="JavaScript">
function pokaz(url, szer, wys) {
cnfig = 'toolbar=no,location=no,directories=no, status=no,menubar=no,width=';
cnfig += szer;
cnfig += ', height='; 
cnfig += wys;
cnfig += ', scrollbars=no,resizable=no';
pop = window.open(url, 'AndreasOnLine', cnfig);
}
</script>

<p align="center" class="9ptV">
<a href="rork1gal1.php"><img border="0" src="../img/rork1/01s.jpg" width="159" height="213"></a><br>
                      <br>
<A HREF="javascript:pokaz('../img/rork1/02a.jpg','357','480');"><IMG SRC="../img/rork1/02s.jpg" HSPACE=0 VSPACE=0 BORDER=0></A><br>
                      <br>
                      <a href="rork1gal3.php">
                      <img border="0" src="../img/rork1/03s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal4.php">
                      <img border="0" src="../img/rork1/04s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal5.php">
                      <img border="0" src="../img/rork1/05s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal6.php">
                      <img border="0" src="../img/rork1/06s.jpg" width="159" height="213"></a><br>
                      <br>
<a href="rork1gal7.php">
                      <img border="0" src="../img/rork1/07s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal8.php">
                      <img border="0" src="../img/rork1/08s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal9.php">
                      <img border="0" src="../img/rork1/09s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal10.php">
                      <img border="0" src="../img/rork1/10s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal11.php">
                      <img border="0" src="../img/rork1/11s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal12.php">
                      <img border="0" src="../img/rork1/12s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork1gal13.php">
                      <img border="0" src="../img/rork1/13s.jpg" width="159" height="213"></a><br>
                      <br>
                      </p>