            <td width="100%" height="140" background="../img/top2.jpg" style="border-bottom: 1 solid #000000" valign="top">
              <div align="right">
                <table border="0" width="122" cellspacing="0" cellpadding="0">
                  <tr>
                    <td width="113" align="right"><a onmouseover="document['fpAnimswapImgFP1'].imgRolln=document['fpAnimswapImgFP1'].src;document['fpAnimswapImgFP1'].src=document['fpAnimswapImgFP1'].lowsrc;" onmouseout="document['fpAnimswapImgFP1'].src=document['fpAnimswapImgFP1'].imgRolln" href="crom1.php"><img border="0" src="../img/nap_crom_b.gif" id="fpAnimswapImgFP1" name="fpAnimswapImgFP1" dynamicanimation="fpAnimswapImgFP1" lowsrc="../img/nap_crom_b2.gif" width="113" height="28"></a></td>
                    <td width="9" align="right"></td>
                  </tr>
                  <tr>
                    <td width="113" align="right"><a onmouseover="document['fpAnimswapImgFP7'].imgRolln=document['fpAnimswapImgFP7'].src;document['fpAnimswapImgFP7'].src=document['fpAnimswapImgFP7'].lowsrc;" onmouseout="document['fpAnimswapImgFP7'].src=document['fpAnimswapImgFP7'].imgRolln" href="cap1.php"><img border="0" src="../img/nap_cap_b.gif" id="fpAnimswapImgFP7" name="fpAnimswapImgFP7" dynamicanimation="fpAnimswapImgFP7" lowsrc="../img/nap_cap_b2.gif" width="89" height="22"></a></td>
                    <td width="9" align="right"></td>
                  </tr>
                  <tr>
                    <td width="113" align="right"><a onmouseover="document['fpAnimswapImgFP8'].imgRolln=document['fpAnimswapImgFP8'].src;document['fpAnimswapImgFP8'].src=document['fpAnimswapImgFP8'].lowsrc;" onmouseout="document['fpAnimswapImgFP8'].src=document['fpAnimswapImgFP8'].imgRolln" href="mob1.php"><img border="0" src="../img/nap_mob_b.gif" id="fpAnimswapImgFP8" name="fpAnimswapImgFP8" dynamicanimation="fpAnimswapImgFP8" lowsrc="../img/nap_mob_b2.gif" width="55" height="22"></a></td>
                    <td width="9" align="right"></td>
                  </tr>
                  <tr>
                    <td width="113" align="right"><a onmouseover="document['fpAnimswapImgFP22'].imgRolln=document['fpAnimswapImgFP22'].src;document['fpAnimswapImgFP22'].src=document['fpAnimswapImgFP22'].lowsrc;" onmouseout="document['fpAnimswapImgFP22'].src=document['fpAnimswapImgFP22'].imgRolln" href="rork1.php"><img border="0" src="../img/nap_rork_b.gif" id="fpAnimswapImgFP22" name="fpAnimswapImgFP22" dynamicanimation="fpAnimswapImgFP22" lowsrc="../img/nap_rork_b2.gif" width="42" height="21"></a></td>
                    <td width="9" align="right"></td>
                  </tr>
                  <tr>
                    <td width="113" align="right"><a onmouseover="document['fpAnimswapImgFP20'].imgRolln=document['fpAnimswapImgFP20'].src;document['fpAnimswapImgFP20'].src=document['fpAnimswapImgFP20'].lowsrc;" onmouseout="document['fpAnimswapImgFP20'].src=document['fpAnimswapImgFP20'].imgRolln" href="arq.php"><img border="0" src="../img/nap_arq_b.gif" id="fpAnimswapImgFP20" name="fpAnimswapImgFP20" dynamicanimation="fpAnimswapImgFP20" lowsrc="../img/nap_arq_b2.gif" width="32" height="22"></a></td>
                    <td width="9" align="right"></td>
                  </tr>
                  <tr>
                    <td width="113" align="right"><a onmouseover="document['fpAnimswapImgFP21'].imgRolln=document['fpAnimswapImgFP21'].src;document['fpAnimswapImgFP21'].src=document['fpAnimswapImgFP21'].lowsrc;" onmouseout="document['fpAnimswapImgFP21'].src=document['fpAnimswapImgFP21'].imgRolln" href="inne.php"><img border="0" src="../img/nap_inne_b.gif" id="fpAnimswapImgFP21" name="fpAnimswapImgFP21" dynamicanimation="fpAnimswapImgFP21" lowsrc="../img/nap_inne_b2.gif" width="37" height="19"></a></td>
                    <td width="9" align="right"></td>
                  </tr>
                </table>
              </div>
            </td>
