                      <p align="center" class="9ptV"><a href="rork2gal1.php"><img border="0" src="../img/02_okladka_b.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork2gal2.php">
                      <img border="0" src="../img/02_strona1.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork2gal3.php">
                      <img border="0" src="../img/02_strona2.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork2gal4.php">
                      <img border="0" src="../img/02_strona3.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork2gal5.php">
                      <img border="0" src="../img/02_strona6.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork2gal6.php">
                      <img border="0" src="../img/02_strona7.jpg" width="159" height="213"></a><br>
                      <br>
                      </p>