                      <p align="center" class="9ptV">
                      <a href="rork6gal1.php">
                      <img border="0" src="../img/rork6/01s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork6gal2.php">
                      <img border="0" src="../img/rork6/02s.jpg" width="159" height="213"></a><br>
                      <br>
                      <a href="rork6gal3.php">
                      <img border="0" src="../img/rork6/03s.jpg" width="159" height="213"></a><br>
                      </p>